name: Generate ASCII Artwork

on:
    push:
        branches:
            - master
            - main

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Executing shell script
              run: |
                  chmod +x ascii-generator.sh
                  ./ascii-generator.sh
