name: First Github Workflow

on:
    push:
        branches:
            - master
            - main

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"

            - name: List all the files in the repository
              run: ls -R

            - name: Read readme.md file
              run: cat README.md
