name: Generate ASCII Artwork

on:
    push:
        branches:
            - master
            - main

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install cowsay package
              run: sudo apt-get install cowsay -y

            - name: Generate ASCII Art
              run: cowsay -f dragon "Run for cover, I am a Dragon.. RAWR" > dragon.txt

            - name: Testing if file exist
              run: grep -i "dragon" dragon.txt

            - name: Display ASCII Art
              run: cat dragon.txt

            - name: List all the files in the repository
              run: ls -ltr
