name: Run Multiple Jobs

on:
    push:
        branches:
            - master
            - main

jobs:
    build_job_one:
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: sudo apt-get install -y cowsay

            - name: Executing cowsay
              run: cowsay -f dragon "Run for cover, I am a Dragon!" >> dragon.txt

            - name: Upload Artifacts for further processing
              uses: actions/upload-artifact@v3
              with:
                  name: dragon-artifact
                  path: dragon.txt

            - name: sleeping for 10 seconds
              run: sleep 10

    test_job_two:
        runs-on: ubuntu-latest
        needs: build_job_one
        steps:
            - name: sleeping for 10 seconds
              run: sleep 10

            - name: Download Artifacts for further processing
              uses: actions/download-artifact@v3
              with:
                  name: dragon-artifact

            - name: Testin file existence
              run: grep -i "dragon" dragon.txt

    deploy_job_three:
        runs-on: ubuntu-latest
        needs: test_job_two
        steps:
            - name: sleeping for 10 seconds
              run: sleep 10.

            - name: Download Artifacts for further processing
              uses: actions/download-artifact@v3
              with:
                  name: dragon-artifact

            - name: Reading the file
              run: cat dragon.txt
